[package]
name = "aglan/s2-weapon-system"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Charm = "littensy/charm@0.10.0"
CharmSync = "littensy/charm-sync@0.3.0"

[server-dependencies]
